version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  # ------------------------------------------
# Default Administrator User
# Email:    admin@example.com
# Password: changeme
# ------------------------------------------
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '443:443'
      # Admin Web Port:
      - '82:82'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

